%%{init: {"flowchart": {"curve": "linear", "htmlLabels": false}} }%%
flowchart TB
    A(["Start"]) --> B[/Data Acquisition/]
    B --> C["Data Pre-processing"]
    C --> D["Data Splitting"]

    D --> E[("Test Set")]
    D --> F[("Validation Set")]
    D --> G[("Training Set")]

    G --> H["Data Augmentation<br/>(Training Only)"]
    H --> I["Model Development"]
    I --> J["Model Training"]
    F --> K["Hyperparameter Tuning"]
    J --> K
    K --> L{"Validation Accuracy,<br/>Loss, and F1-Score<br/>Satisfactory?"}

    L -->|No| J
    L -->|Yes| M["Save Best Model"]

    M --> N["Model Evaluation<br/>(Accuracy, Precision,<br/>Recall, F1-Score,<br/>Confusion Matrix)"]
    E --> N
    N --> O["Grad-CAM"]
    O --> P[/Output Results/]
    P --> Q(["End"])
